settings:
  log_level: info
mappings:
  - name: Demo
    input:
      plugin: csv
      config:
        path: /home/ceyhun/projects/tractor/.test/data
        file: movies.csv
        header: true
    output:
      plugin: json
      config:
        path: /home/ceyhun/projects/tractor/.test/data
        file: movies_out.json
      catalog:
        name: movies
        auto_map_fields: true
        fields:
          - name: year
            type: integer
