settings:
  log_level: info

connections:
  aws_s3:
    connector: file
    config:
      access_key_id: "AKIAJX3ZQ3X7ZQ7X3X3Q"
      secret_access_key: "ZQ7X3X3Q7X3X3X3X3X3X3X3X3X3X3X3X3X3X3X3X3X3X3X3X3X3X3X3X3X3"
      provider:
        type: s3
        aws_access_key_id: "AKIAIOSFODNN7EXAMPLE"
        aws_secret_access_key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
      options:
        header: true
        delimiter: ","

mappings:
  Demo:
    input:
      connection: aws_s3
    output:
      connection: aws_s3
      catalog:
        name: x
