<div class="loadingio-spinner-cube-igxtpjxsigq">
	<div class="ldio-9e94en9iwiv">
		<div />
		<div />
		<div />
		<div />
	</div>
</div>

<style type="text/css">
	@keyframes ldio-9e94en9iwiv {
		0% {
			transform: scale(1.1500000000000001);
		}
		100% {
			transform: scale(1);
		}
	}
	.ldio-9e94en9iwiv div {
		position: absolute;
		width: 40px;
		height: 40px;
		top: 6.666666666666668px;
		left: 6.666666666666668px;
		background: #e15b64;
		animation: ldio-9e94en9iwiv 1s cubic-bezier(0, 0.5, 0.5, 1) infinite;
		animation-delay: -0.3s;
	}
	.ldio-9e94en9iwiv div:nth-child(2) {
		top: 6.666666666666668px;
		left: 53.33333333333333px;
		background: #f47e60;
		animation-delay: -0.2s;
	}
	.ldio-9e94en9iwiv div:nth-child(3) {
		top: 53.33333333333333px;
		left: 6.666666666666668px;
		background: #abbd81;
		animation-delay: 0s;
	}
	.ldio-9e94en9iwiv div:nth-child(4) {
		top: 53.33333333333333px;
		left: 53.33333333333333px;
		background: #f8b26a;
		animation-delay: -0.1s;
	}
	.loadingio-spinner-cube-igxtpjxsigq {
		width: 69px;
		height: 69px;
		display: inline-block;
		overflow: hidden;
		background: #ffffff;
	}
	.ldio-9e94en9iwiv {
		width: 100%;
		height: 100%;
		position: relative;
		transform: translateZ(0) scale(0.69);
		backface-visibility: hidden;
		transform-origin: 0 0; /* see note above */
	}
	.ldio-9e94en9iwiv div {
		box-sizing: content-box;
	}
	/* generated by https://loading.io/ */

	.loadingio-spinner-cube-igxtpjxsigq {
		position: absolute;
		left: 50%;
		top: 50%;
		transform: translate(-50%, -50%);
		background: unset;
	}
</style>
